export const UPDATE_FILTER = 'UPDATE_FILTER';
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM';
export const LOAD_RESTAURANTS_SUCCESS = 'LOAD_RESTAURANTS_SUCCESS';
export const LOADING_RESTAURANTS = 'LOADING_RESTAURANTS';
export const LOAD_RESTAURANTS_FAIL = 'LOAD_RESTAURANTS_FAIL';
export const INCREASE_PAGER_NUM = 'INCREASE_PAGER_NUM';
export const DECREASE_PAGER_NUM = 'DECREASE_PAGER_NUM';
